create extension if not exists pgcrypto;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Wigs', 'Bundles', 'Closures_Frontals', 'Hair_Care')),
  price numeric(12, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  description text not null default '',
  image_urls text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid references users (id) on delete set null,
  customer_email text,
  items jsonb not null default '[]'::jsonb,
  total_price numeric(12, 2) not null check (total_price >= 0),
  order_status text not null default 'Pending' check (order_status in ('Pending', 'Confirmed', 'Delivered')),
  shipping_name text not null,
  shipping_phone text not null,
  shipping_address text not null,
  payment_ref text not null,
  created_at timestamptz not null default now()
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  user_id uuid not null references users (id) on delete cascade,
  username text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_category on products (category);
create index if not exists idx_orders_user_id on orders (user_id);
create index if not exists idx_orders_created_at on orders (created_at desc);
create index if not exists idx_reviews_product_id on reviews (product_id);
create index if not exists idx_users_email on users (email);
